spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_36
    username: nhn_academy_36
    password: LE./7B[CZtN1T0SA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  session:
    timeout: 18000

server:
  port: 8081

api:
  account-service:
    base-url: http://localhost:8081
  project-service:
    base-url: http://localhost:8082

# Uncomment and configure the following lines if you want to use GitHub OAuth2
# spring:
#   security:
#     oauth2:
#       client:
#         registration:
#           github:
#             client-id: yourclientid
#             client-secret: yourclientsecret
#             scope: read:user
#             redirect-uri: "{baseUrl}/login/oauth2/code/github"
#             client-name: GitHub
